#!/bin/bash
yum update -y
yum remove -y awscli
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl
chmod +x ./kubectl
HOME=/home/ec2-user
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
echo 'alias k=kubectl' >> ~/.bashrc
echo "alias test_eks='aws eks --region ap-northeast-2 update-kubeconfig --name hyeonju-cluster'" >> ~/.bashrc
source ~/.bashrc
sed -i "s|#Port 22|Port 1022|g" /etc/ssh/sshd_config
systemctl restart sshd
